[project]
name = "digital-attendance-pro"
version = "1.0.0"
description = "Digital Attendance Pro"
requires-python = ">=3.10"
dependencies = [
    "flet",
    "flet-geolocator",
]

[tool.flet]
org = "com.example"
product = "Digital Attendance Pro"

[tool.flet.android.permission]
"android.permission.ACCESS_FINE_LOCATION" = true
"android.permission.ACCESS_COARSE_LOCATION" = true